name: Ejecutar limpieza cada 5 minutos

on:
  schedule:
    - cron: '*/5 * * * *'  # Cada 5 minutos
  workflow_dispatch:        # También puedes ejecutarlo manualmente

jobs:
  ejecutar-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar notebook
        run: |
          pip install papermill
          papermill limpieza_forms.ipynb salida.ipynb
